### ISSUE TITLE
jest-vue-report运行的时候报错

### ISSUE THREAD

**Issue by Baiang** [lenvonsam/vue-jest-test#1]
FAIL  test\unit\integration\login.spec.js
  ● Test suite failed to run

    Cannot find module 'undefined/package.json' from 'index.min.js'

      at Resolver.resolveModule (node_modules/_jest-resolve@22.4.3@jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/_jest-vue-report@0.1.5@jest-vue-report/dist/index.min.js:1:119)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.714s
Ran all test suites.
Error: Cannot find module 'undefined/package.json'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (F:\website\vue-2.0\node_modules\_jest-vue-report@0.1.5@jest-vue-report\dist\index.min.js:1:92)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vuedemo@1.0.0 unit: `jest --config test/unit/jest.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vuedemo@1.0.0 unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\wiwi\node\node-cache\_logs\2018-07-05T03_21_47_359Z-debug.log

**Comment by lenvonsam** [comment]
It is recommended to use gitbash instead of CMD window
